In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score

In [2]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_55c8f9b7e5d84cdc8a1c2f8bd91ebb54 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='qivYxRxHZ96ugUgH_E2j2iY2cR66VCfKE6DpgFzAoyep',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_55c8f9b7e5d84cdc8a1c2f8bd91ebb54.get_object(Bucket='lifeexpectancyprediction-donotdelete-pr-xddpev2n8i1hkq',Key='Life Expectancy Data (Edited).csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset.head()


Country  Year      Status  Adult Mortality  infant deaths  Alcohol  \
0  Afghanistan  2015  Developing            263.0             62     0.01   
1  Afghanistan  2014  Developing            271.0             64     0.01   
2  Afghanistan  2013  Developing            268.0             66     0.01   
3  Afghanistan  2012  Developing            272.0             69     0.01   
4  Afghanistan  2011  Developing            275.0             71     0.01   

   percentage expenditure  Hepatitis B  Measles    BMI   ...  \
0               71.279624         65.0      1154   19.1  ...   
1               73.523582         62.0       492   18.6  ...   
2               73.219243         64.0       430   18.1  ...   
3               78.184215         67.0      2787   17.6  ...   
4                7.097109         68.0      3013   17.2  ...   

   Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0               8.16         65.0        0.1  584.259210  33736494.0   
1               8.18         62.0        0.1  612.696514    327582.0   
2               8.13         64.0        0.1  631.744976  31731688.0   
3               8.52         67.0        0.1  669.959000   3696958.0   
4               7.87         68.0        0.1   63.537231   2978599.0   

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3   
1                   17.5                 17.5   
2                   17.7                 17.7   
3                   17.9                 18.0   
4                   18.2                 18.2   

   Income composition of resources  Schooling  Life expectancy   
0                            0.479       10.1              65.0  
1                            0.476       10.0              59.9  
2                            0.470        9.9              59.9  
3                            0.463        9.8              59.5  
4                            0.454        9.5              59.2  

[5 rows x 22 columns]

In [3]:
# dataset = pd.read_csv('Life Expectancy Data.csv')
value_counts = dataset['Country'].value_counts()
to_remove = value_counts[value_counts == 1].index
dataset = dataset[~dataset.Country.isin(to_remove)]
dataset

Country  Year      Status  Adult Mortality  infant deaths  Alcohol  \
0     Afghanistan  2015  Developing            263.0             62     0.01   
1     Afghanistan  2014  Developing            271.0             64     0.01   
2     Afghanistan  2013  Developing            268.0             66     0.01   
3     Afghanistan  2012  Developing            272.0             69     0.01   
4     Afghanistan  2011  Developing            275.0             71     0.01   
5     Afghanistan  2010  Developing            279.0             74     0.01   
6     Afghanistan  2009  Developing            281.0             77     0.01   
7     Afghanistan  2008  Developing            287.0             80     0.03   
8     Afghanistan  2007  Developing            295.0             82     0.02   
9     Afghanistan  2006  Developing            295.0             84     0.03   
10    Afghanistan  2005  Developing            291.0             85     0.02   
11    Afghanistan  2004  Developing            293.0             87     0.02   
12    Afghanistan  2003  Developing            295.0             87     0.01   
13    Afghanistan  2002  Developing              3.0             88     0.01   
14    Afghanistan  2001  Developing            316.0             88     0.01   
15    Afghanistan  2000  Developing            321.0             88     0.01   
16        Albania  2015  Developing             74.0              0     4.60   
17        Albania  2014  Developing              8.0              0     4.51   
18        Albania  2013  Developing             84.0              0     4.76   
19        Albania  2012  Developing             86.0              0     5.14   
20        Albania  2011  Developing             88.0              0     5.37   
21        Albania  2010  Developing             91.0              1     5.28   
22        Albania  2009  Developing             91.0              1     5.79   
23        Albania  2008  Developing              1.0              1     5.61   
24        Albania  2007  Developing              9.0              1     5.58   
25        Albania  2006  Developing             99.0              1     5.31   
26        Albania  2005  Developing             15.0              1     5.16   
27        Albania  2004  Developing             17.0              1     4.54   
28        Albania  2003  Developing             18.0              1     4.29   
29        Albania  2002  Developing             15.0              1     3.73   
...           ...   ...         ...              ...            ...      ...   
2908       Zambia  2013  Developing            328.0             29     2.41   
2909       Zambia  2012  Developing            349.0             29     2.59   
2910       Zambia  2011  Developing            366.0             29     2.57   
2911       Zambia  2010  Developing            363.0             30     2.47   
2912       Zambia  2009  Developing            368.0             30     2.30   
2913       Zambia  2008  Developing             45.0             31     2.12   
2914       Zambia  2007  Developing            487.0             32     2.08   
2915       Zambia  2006  Developing            526.0             33     2.25   
2916       Zambia  2005  Developing            554.0             34     2.33   
2917       Zambia  2004  Developing            578.0             36     2.46   
2918       Zambia  2003  Developing             64.0             39     2.33   
2919       Zambia  2002  Developing             69.0             41     2.44   
2920       Zambia  2001  Developing            611.0             43     2.61   
2921       Zambia  2000  Developing            614.0             44     2.62   
2922     Zimbabwe  2015  Developing            336.0             22      NaN   
2923     Zimbabwe  2014  Developing            371.0             23     6.50   
2924     Zimbabwe  2013  Developing            399.0             25     6.39   
2925     Zimbabwe  2012  Developing            429.0             26     6.09   
2926     Z

In [4]:
df = dataset

In [5]:
countries = pd.unique(dataset['Country'])

In [6]:
country_index = {k: v for v, k in enumerate(countries)}
status_index = {'Developed': 0, 'Developing':1}

In [7]:
country_index

{'Afghanistan': 0,
 'Albania': 1,
 'Algeria': 2,
 'Angola': 3,
 'Antigua and Barbuda': 4,
 'Argentina': 5,
 'Armenia': 6,
 'Australia': 7,
 'Austria': 8,
 'Azerbaijan': 9,
 'Bahamas': 10,
 'Bahrain': 11,
 'Bangladesh': 12,
 'Barbados': 13,
 'Belarus': 14,
 'Belgium': 15,
 'Belize': 16,
 'Benin': 17,
 'Bhutan': 18,
 'Plurinational State of Bolivia': 19,
 'Bosnia and Herzegovina': 20,
 'Botswana': 21,
 'Brazil': 22,
 'Brunei Darussalam': 23,
 'Bulgaria': 24,
 'Burkina Faso': 25,
 'Burundi': 26,
 "Côte d'Ivoire": 27,
 'Cabo Verde': 28,
 'Cambodia': 29,
 'Cameroon': 30,
 'Canada': 31,
 'Central African Republic': 32,
 'Chad': 33,
 'Chile': 34,
 'China': 35,
 'Colombia': 36,
 'Comoros': 37,
 'Congo': 38,
 'Costa Rica': 39,
 'Croatia': 40,
 'Cuba': 41,
 'Cyprus': 42,
 'Czechia': 43,
 "Democratic People's Republic of Korea": 44,
 'Democratic Republic of the Congo': 45,
 'Denmark': 46,
 'Djibouti': 47,
 'Dominican Republic': 48,
 'Ecuador': 49,
 'Egypt': 50,
 'El Salvador': 51,
 'Equatorial Gu

In [8]:
df['Country'] = df['Country'].replace(country_index, regex=True)
df['Status'] = df['Status'].replace(status_index,regex=True)
df

Country  Year  Status  Adult Mortality  infant deaths  Alcohol  \
0           0  2015       1            263.0             62     0.01   
1           0  2014       1            271.0             64     0.01   
2           0  2013       1            268.0             66     0.01   
3           0  2012       1            272.0             69     0.01   
4           0  2011       1            275.0             71     0.01   
5           0  2010       1            279.0             74     0.01   
6           0  2009       1            281.0             77     0.01   
7           0  2008       1            287.0             80     0.03   
8           0  2007       1            295.0             82     0.02   
9           0  2006       1            295.0             84     0.03   
10          0  2005       1            291.0             85     0.02   
11          0  2004       1            293.0             87     0.02   
12          0  2003       1            295.0             87     0.01   
13          0  2002       1              3.0             88     0.01   
14          0  2001       1            316.0             88     0.01   
15          0  2000       1            321.0             88     0.01   
16          1  2015       1             74.0              0     4.60   
17          1  2014       1              8.0              0     4.51   
18          1  2013       1             84.0              0     4.76   
19          1  2012       1             86.0              0     5.14   
20          1  2011       1             88.0              0     5.37   
21          1  2010       1             91.0              1     5.28   
22          1  2009       1             91.0              1     5.79   
23          1  2008       1              1.0              1     5.61   
24          1  2007       1              9.0              1     5.58   
25          1  2006       1             99.0              1     5.31   
26          1  2005       1             15.0              1     5.16   
27          1  2004       1             17.0              1     4.54   
28          1  2003       1             18.0              1     4.29   
29          1  2002       1             15.0              1     3.73   
...       ...   ...     ...              ...            ...      ...   
2908      181  2013       1            328.0             29     2.41   
2909      181  2012       1            349.0             29     2.59   
2910      181  2011       1            366.0             29     2.57   
2911      181  2010       1            363.0             30     2.47   
2912      181  2009       1            368.0             30     2.30   
2913      181  2008       1             45.0             31     2.12   
2914      181  2007       1            487.0             32     2.08   
2915      181  2006       1            526.0             33     2.25   
2916      181  2005       1            554.0             34     2.33   
2917      181  2004       1            578.0             36     2.46   
2918      181  2003       1             64.0             39     2.33   
2919      181  2002       1             69.0             41     2.44   
2920      181  2001       1            611.0             43     2.61   
2921      181  2000       1            614.0             44     2.62   
2922      182  2015       1            336.0             22      NaN   
2923      182  2014       1            371.0             23     6.50   
2924      182  2013       1            399.0             25     6.39   
2925      182  2012       1            429.0             26     6.09   
2926      182  2011       1            464.0             28     6.00   
2927      182  2010       1            527.0             29     5.21   
2928      182  2009       1            587.0             30     4.64   
2929      182  2008       1            632.0             30     3.56   
2930      182  2007       1             67.0             29     3.88   
2931      182  2006       1              7.0  

In [9]:
train = df[df['Year'] != 2015].values
# train = train[train['Year'] != 2014 ]
# train = train[train['Year'] != 2013 ]
# train = train.values
train.shape

(2745, 22)

In [10]:
X_train = train[:,:-1]
X_train

array([[0.000e+00, 2.014e+03, 1.000e+00, ..., 1.750e+01, 4.760e-01,
        1.000e+01],
       [0.000e+00, 2.013e+03, 1.000e+00, ..., 1.770e+01, 4.700e-01,
        9.900e+00],
       [0.000e+00, 2.012e+03, 1.000e+00, ..., 1.800e+01, 4.630e-01,
        9.800e+00],
       ...,
       [1.820e+02, 2.002e+03, 1.000e+00, ..., 1.300e+00, 4.270e-01,
        1.000e+01],
       [1.820e+02, 2.001e+03, 1.000e+00, ..., 1.700e+00, 4.270e-01,
        9.800e+00],
       [1.820e+02, 2.000e+03, 1.000e+00, ..., 1.120e+01, 4.340e-01,
        9.800e+00]])

In [11]:
y_train = train[:,-1]
y_train

array([59.9, 59.9, 59.5, ..., 44.8, 45.3, 46. ])

In [12]:
test = df[df['Year'] == 2015].values
# test = test.append(dataset[dataset['Year'] == 2014 ])
# test = test.append(dataset[dataset['Year'] == 2013 ])
# test = test.values
test

array([[0.000e+00, 2.015e+03, 1.000e+00, ..., 4.790e-01, 1.010e+01,
        6.500e+01],
       [1.000e+00, 2.015e+03, 1.000e+00, ..., 7.620e-01, 1.420e+01,
        7.780e+01],
       [2.000e+00, 2.015e+03, 1.000e+00, ..., 7.430e-01, 1.440e+01,
        7.560e+01],
       ...,
       [1.800e+02, 2.015e+03, 1.000e+00, ..., 4.990e-01, 9.000e+00,
        6.570e+01],
       [1.810e+02, 2.015e+03, 1.000e+00, ..., 5.760e-01, 1.250e+01,
        6.180e+01],
       [1.820e+02, 2.015e+03, 1.000e+00, ..., 5.070e-01, 1.030e+01,
        6.700e+01]])

In [13]:
X_test = test[:,:-1]
X_test.shape

(183, 21)

In [14]:
y_test = test[:,-1]
y_test.shape

(183,)

In [15]:
imputer = SimpleImputer(missing_values=np.nan , strategy = 'constant', fill_value= 0)
X_train[:,3:] = imputer.fit_transform(X_train[:,3:])
X_test[:,3:] = imputer.fit_transform(X_test[:,3:])

In [16]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
y_pred = regressor.predict(X_test)

In [18]:
y_pred

array([60.11019605, 74.98284341, 74.28957027, 58.38118684, 74.05845615,
       74.21731933, 71.58987103, 81.12433991, 78.47936322, 71.58498412,
       71.66505663, 74.64978737, 67.37595129, 73.48191507, 71.8898031 ,
       77.27621963, 67.44996295, 63.45822499, 65.99076257, 70.58738787,
       71.84568595, 66.57329794, 73.31598977, 72.66818483, 75.01374455,
       67.02431165, 63.23036845, 56.66682533, 69.73266043, 67.19697471,
       60.52143718, 76.9323698 , 55.59581919, 55.92565498, 75.19575827,
       73.87701804, 71.47835528, 65.42533896, 58.74564105, 69.86063635,
       76.63945764, 73.31840686, 73.80673641, 70.18733879, 64.58445554,
       60.21582659, 77.05761087, 63.8585    , 71.08299773, 71.48830359,
       71.97670895, 70.74571786, 62.86853043, 63.22866742, 73.51414949,
       63.03987467, 71.87343667, 74.5092555 , 76.70568659, 63.48205946,
       64.17476726, 72.26252998, 79.40878754, 65.5495753 , 75.53769702,
       72.20196824, 64.16636549, 60.62082929, 62.62735656, 68.27

In [19]:
error = []
for i in range(len(y_test)):
    a=abs(y_test[i]-y_pred[i])
    error.append(a)
acc=100-(sum(error)/len(y_test))

In [20]:
acc

96.73850225487487

In [21]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

wml_credentials = {
  "apikey": "lgm-DVOeiPYBfflS-5syMGObsUo6BUc-HBechBnLFXOM",
  "iam_apikey_description": "Auto-generated for key b7c961c4-bde1-487e-8ae6-6a75e975836c",
  "iam_apikey_name": "Service credentials-1",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/590c8c1116104bd198a4022cb49d1c4f::serviceid:ServiceId-b06d6c31-5bb8-462e-9e33-5e4254f037e2",
  "instance_id": "a0f87c50-083c-4d96-8311-c128f9a48201",
  "url": "https://eu-gb.ml.cloud.ibm.com"
}
client = WatsonMachineLearningAPIClient(wml_credentials)
print(client.version)

1.0.378


In [22]:
# Use this cell to do any cleanup of previously created models and deployments
client.repository.list_models()
client.deployments.list()

# client.repository.delete('GUID of stored model')
# client.deployments.delete('GUID of deployed model'

----  ----  -------  ---------
GUID  NAME  CREATED  FRAMEWORK
----  ----  -------  ---------
----  ----  ----  -----  -------  ---------  -------------
GUID  NAME  TYPE  STATE  CREATED  FRAMEWORK  ARTIFACT TYPE
----  ----  ----  -----  -------  ---------  -------------


In [23]:
meta_props={client.repository.ModelMetaNames.NAME: "Life Expectancy Prediction Model"}
published_model = client.repository.store_model(model=regressor, meta_props={client.repository.ModelMetaNames.NAME: "Life Expectancy Prediction Model"})

In [24]:
client.repository.list_models()

# get UID of our just stored model
model_uid = client.repository.get_model_uid(published_model)
print("Model id: {}".format(model_uid))

------------------------------------  --------------------------------  ------------------------  -----------------
GUID                                  NAME                              CREATED                   FRAMEWORK
0b041d2c-653b-4698-b670-494544242697  Life Expectancy Prediction Model  2020-06-28T18:55:29.174Z  scikit-learn-0.20
------------------------------------  --------------------------------  ------------------------  -----------------
Model id: 0b041d2c-653b-4698-b670-494544242697


In [25]:
created_deployment = client.deployments.create(model_uid, name="life_exp_pred_model")

# new list of deployments
client.deployments.list()

# get UID of our new deployment
deployment_uid = client.deployments.get_uid(created_deployment)
print("Deployment id: {}".format(deployment_uid))
print(created_deployment)



#######################################################################################

Synchronous deployment creation for uid: '0b041d2c-653b-4698-b670-494544242697' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='10ab5622-939c-43a4-a02f-d09a90bca830'
------------------------------------------------------------------------------------------------


------------------------------------  -------------------  ------  --------------  ------------------------  -----------------  -------------
GUID                                  NAME                 TYPE    STATE           CREATED                   FRAMEWORK          ARTIFACT TYPE
10ab5622-939c-43a4-a02f-d09a90bca830  life_exp_pred_model  online  DEPLOY_SUCCESS  2020-06-28T18:55:43.004Z  scikit-learn-0

In [26]:
scoring_endpoint = client.deployments.get_scoring_url(created_deployment)
print(scoring_endpoint)

https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/a0f87c50-083c-4d96-8311-c128f9a48201/deployments/10ab5622-939c-43a4-a02f-d09a90bca830/online
